name: Dorothy Day Collection
description: Collection of Dorothy Day's writings

url: http://dorothyday.catholicworker.org
baseurl: /

auto: true
server: true

markdown: kramdown

exclude: Makefile



